const ORIGIN = 'https://shridaaarts.com';
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
function artworkPage(art) {
  const url = `${ORIGIN}/artwork/${encodeURIComponent(art.slug)}/`;
  const image = `${ORIGIN}/${art.image.replace(/^\//, '')}`;
  const visible = art.isPriceVisible !== false && art.price !== null;
  const price = visible ? `₹${Number(art.price).toLocaleString('en-IN')}` : 'Price on Request';
  const enquiry = `Hello Ashima, I am interested in ${art.name}${visible ? ` (${price}, shipping excluded)` : ''}. Could you share ordering and shipping details?`;
  const product = { '@context':'https://schema.org', '@type':'Product', name:art.name, description:art.shortDescription, image, url, brand:{'@type':'Brand',name:'Shridaa Arts'}, ...(visible ? { offers:{'@type':'Offer', price:art.price, priceCurrency:'INR', availability:art.availability === 'Sold' ? 'https://schema.org/OutOfStock' : art.availability === 'Made to Order' ? 'https://schema.org/PreOrder' : 'https://schema.org/InStock', url} } : {}) };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(art.name)} | Shridaa Arts</title><meta name="description" content="${escape(art.shortDescription)}"><link rel="canonical" href="${url}"><meta property="og:type" content="product"><meta property="og:url" content="${url}"><meta property="og:title" content="${escape(art.name)}"><meta property="og:description" content="${escape(art.shortDescription)}"><meta property="og:image" content="${escape(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${escape(image)}"><link rel="stylesheet" href="../../css/style.css"><script type="application/ld+json">${JSON.stringify(product).replace(/</g,'\\u003c')}</script></head><body class="site-body"><header class="container section"><a class="brand-title" href="../../">SHRIDAA ARTS</a></header><main class="container section product-page"><a class="back-link" href="../../#artworks">← All Artworks</a><article><h1>${escape(art.name)}</h1><p>${escape(art.category)} · ${escape(art.availability)}</p><img class="product-image" src="../../${escape(art.image.replace(/^\//,''))}" alt="${escape(art.name)}" width="800" height="800"><h2>${escape(price)}</h2>${visible && art.originalPrice ? `<p><s>₹${Number(art.originalPrice).toLocaleString('en-IN')}</s></p>` : ''}<p>Shipping excluded; calculated for your location.</p><p>${escape(art.detailedDescription || art.shortDescription)}</p><dl><dt>Dimensions</dt><dd>${escape(art.size || 'Ask the studio')}</dd><dt>Materials</dt><dd>${escape(art.material)}</dd><dt>Customization</dt><dd>${art.isCustomizable ? 'Available; contact Ashima for details' : 'Standard design'}</dd></dl><div class="product-actions"><a class="btn btn-whatsapp" href="https://wa.me/919983466388?text=${encodeURIComponent(enquiry)}" target="_blank" rel="noopener noreferrer">Enquire on WhatsApp</a><a class="btn btn-secondary" href="../../#artwork=${encodeURIComponent(art.id)}">Open interactive preview & shortlist</a></div><p>Advance payment required. Please discuss shipping, payment and the studio’s return policy before ordering.</p></article></main><footer class="container section"><a href="mailto:shridaaarts@gmail.com">shridaaarts@gmail.com</a> · <a href="tel:+919983466388">+91 9983466388</a></footer></body></html>`;
}
function sitemap(items) {
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"><url><loc>${ORIGIN}/</loc></url>${items.map(a => `<url><loc>${ORIGIN}/artwork/${escape(encodeURIComponent(a.slug))}/</loc><image:image><image:loc>${ORIGIN}/${escape(a.image.replace(/^\//,''))}</image:loc><image:title>${escape(a.name)}</image:title></image:image></url>`).join('')}</urlset>\n`;
}
module.exports = { artworkPage, sitemap, escape };
